plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}
group = mod_group_id
version = "${minecraft_version}-${mod_version}-neoforge"
base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
neoForge {
    version = neo_version
    runs {
        client { client(); gameDirectory = project.file('run-client') }
        server { server(); programArgument '--nogui' }
        gameTestServer { gameDirectory = project.file('run-gametest'); type = 'gameTestServer'; systemProperty 'asb.gametest', 'true' }
        configureEach { systemProperty 'neoforge.enabledGameTestNamespaces', mod_id }
    }
    mods { "${mod_id}" { sourceSet sourceSets.main } }
}
repositories {
    maven { url = 'https://api.modrinth.com/maven'; content { includeGroup 'maven.modrinth' } }
    maven { url = 'https://cursemaven.com'; content { includeGroup 'curse.maven' } }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'; content { includeGroup 'software.bernie.geckolib' } }
    maven { url = 'https://maven.theillusivec4.top'; content { includeGroup 'top.theillusivec4.curios' } }
    maven { url = 'https://maven.kosmx.dev/'; content { includeGroup 'dev.kosmx.player-anim' } }
    maven { url = 'https://code.redspace.io/releases'; content { includeGroup 'io.redspace' } }
    maven { url = 'https://packages.aether-mod.net/Nitrogen'; content { includeGroup 'com.aetherteam.nitrogen' } }
    mavenCentral()
}
dependencies {
    implementation 'maven.modrinth:accessories:Fb55Fgjz'
    runtimeOnly 'maven.modrinth:owo-lib:aDarc4xa'
    compileOnly 'com.aetherteam.nitrogen:nitrogen_internals:1.21.1-1.1.25-neoforge'
    implementation 'maven.modrinth:irons-spells-n-spellbooks:slKLosTb'
    implementation 'maven.modrinth:aether:K5X5qMwG'
    implementation 'software.bernie.geckolib:geckolib-neoforge-1.21.1:4.7.5.1'
    implementation 'top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1'
    implementation 'dev.kosmx.player-anim:player-animation-lib-forge:2.0.1+1.21.1'
    implementation 'io.redspace:irons_lib:1.21.1-2.1.0'
}
tasks.named('processResources', ProcessResources).configure {
    def props = ['minecraft_version', 'minecraft_version_range', 'neo_version_range', 'loader_version_range', 'mod_id', 'mod_name', 'mod_version', 'mod_license', 'mod_authors', 'mod_description'].collectEntries { [(it): project.property(it)] }
    inputs.properties props
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) { expand props }
}
tasks.named('jar', Jar).configure {
    from('LICENSE')
    exclude 'com/aetherspellbooks/gametest/**'
    exclude 'datapacks/asb_gametest_world/**'
    exclude 'data/aether_spellbooks/structure/empty.nbt'
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.compilerArgs += ['-Xmaxerrs', '500']; options.fork = true; options.forkOptions.jvmArgs += ['-Duser.language=en', '-Duser.country=US'] }
